spring.application.name=SistemaBarbearia
spring.data.mongodb.uri=mongodb+srv://admin:${MONGODB_PASSWORD}@barbearia.qymdkkt.mongodb.net/?retryWrites=true&w=majority&appName=Barbearia
spring.data.mongodb.database=Barbearia

api.security.token.secret=${JWT_SECRET:my-secret-key}

app.mail.from=barbernoreply@gmail.com
#sendgrid.api.key=${SENDGRID_API_KEY}

# Configurações de E-mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=barbernoreply@gmail.com
spring.mail.password=${EMAIL_PASSWORD}

# Propriedades de segurança exigidas pelo Gmail
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


logging.file.name=barbearia-app.log

# 2. Para definir o nivel de log para o seu pacote
logging.level.com.example.SistemaBarbearia=DEBUG


google.client-id=371937337967-p15ooidme7215cquofhn50qlb7vhgq78.apps.googleusercontent.com
